USE [AuctionEvents]
GO

/****** Object:  Table [dbo].[Event]    Script Date: 11/3/2018 5:46:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID(N'[dbo].[Event]', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[Event]
	(
		[SequenceID] [BIGINT] IDENTITY(1, 1) NOT NULL,
		[AggregateID] [UNIQUEIDENTIFIER] NOT NULL,
		[Name] [NVARCHAR](300) NOT NULL,
		[Data] [NVARCHAR](MAX) NOT NULL,
		[Version] [INT] NOT NULL,
		[Timestamp] [DATETIME] NOT NULL,
		CONSTRAINT FK_EventSourceEvent FOREIGN KEY (AggregateID) REFERENCES [EventSource](AggregateID),
		CONSTRAINT [PK_Event]
			PRIMARY KEY CLUSTERED ([SequenceID] ASC)
			WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY];
END;
GO




